### PR TITLE
common: remove duplicate

### PR DESCRIPTION
**Pull request by alviteri**
device/qcom/sepolicy/common/device.te:34:ERROR 'duplicate declaration of type/attribute' at token ';' on line 14226:
type rtc_device, dev_type;
checkpolicy:  error(s) encountered while parsing configuration

see string 15: https://android.googlesource.com/platform/external/sepolicy/+/android-m-preview/device.te
see string 80: https://android.googlesource.com/platform/external/sepolicy/+/android-m-preview/file_contexts

Signed-off-by: David Viteri davidteri91@gmail.com

### CODE REVIEW

**Comment by stellirin** [comment]
This needs to be on a different branch, the L branches don't have these errors

**Comment by alviteri** [comment]
@AdFad666 what about this 

device/qcom/sepolicy/common/init_shell.te:3:ERROR 'unknown type init_shell' at token ';' on line 15959:
#for accessing fmradio device node
allow init_shell fm_radio_device:chr_file { open read ioctl };

**Comment by JulienBolard** [comment]
Hi,

Did you manage to compile it using sonyxperiadev device-qcom-sepolicy from master branch?
I have this error because external/sepolicy has evolved and init_shell does not exist anymore:
device/qcom/sepolicy/common/init_shell.te:3:ERROR 'unknown type init_shell' at token ';' on line 15723:

**Comment by stellirin** [comment]
I've never built directly on master and I haven't yet had the time to try building on 'M' branches. I've only tested on the lollipop 5.1 branches, but it looks like we need to make branches for lollipop_mr1 and m-preview.

**Comment by alviteri** [comment]
About this 
https://github.com/alviteri/platform-external-sepolicy/commit/c7594898dbce021677e6444eb855eb591df1097b

**Pull request closed without merging**
