### PR TITLE
Merge from caf/LA.BF64.1.2.2_rb4.7 and caf/LA.BF64.1.2.2_rb4.8

### PR DESCRIPTION
**Pull request by alviteri**
kernel for M is based now on caf/LA.BF64.1.2.2_rb4.8

@jerpelea Do not merge .... will be compiled and test later

### CODE REVIEW

**Comment by alviteri** [comment]
@erikcas, @humberos if you can test this too would be great

**Comment by humberos** [comment]
@alviteri 
Only 1cfa2d8b4e75071706bfca9e17c30fb26d62b204 is breaking kitakami.
So I think we need to move this to platform.

**Comment by alviteri** [comment]
Since karin is using touchfusion XD maybe others but I am not sure lol

**Comment by humberos** [comment]
Now build is fine here (by using #124)

**Comment by erikcas** [comment]
builds running

**Pull request merged**
